version: '2.19.1'

services:
  database:
    container_name: database
    image: mysql:8.0.33
    volumes:
      - mysqlvolume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: helpdesk
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - spring-network

  keycloak:
    container_name: keycloak_internship
    image: quay.io/keycloak/keycloak:22.0
    depends_on:
      - database
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://database/helpdesk
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: root
      KEYCLOAK_HOST: localhost
      KEYCLOAK_PORT: 8080
      KEYCLOAK_REALM: helptask
    ports:
      - "8080:8080"
    command:
      - start-dev
    networks:
      - spring-network

volumes:
  mysqlvolume:

networks:
  spring-network:
    driver: bridge


